### PR TITLE
Merge 3.0.2 to civis branch

### PR DESCRIPTION
**Pull request by mattyb**

### CODE REVIEW

**Comment by mattyb** [comment]
This worked in staging

**Comment by briannic** [comment]
FWIW - it looks like the last two commits to `README.md` are unreleased on master. Still want to to merge this in as part of v3.0.2?

**Comparing v3.0.0 to v3.0.2**
https://github.com/tinfoil/devise-two-factor/compare/v3.0.0...v3.0.2

**Comparing v3.0.0 to master**
https://github.com/tinfoil/devise-two-factor/compare/v3.0.0...master

**Comment by mattyb** [comment]
Yeah, good point. Updated.

**Review by briannic — APPROVED** [review]
LGTM

**Pull request merged**
